# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js seung_cd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: connect seung-server and crawling-cd shell script
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.SEUNGKI_SERVER_IP }}
        username: ${{ secrets.SEUNGKI_SERVER_USERNAME }}
        password: ${{ secrets.SEUNGKI_SERVER_PASSWORD }}
        port: ${{ secrets.SEUNGKI_SERVER_PORT }}
        script: |
          REPOSITORY=/usr/it-hermes-project

          cd $REPOSITORY/IT-Hermes-Crawling

          echo "> Git Pull"

          git pull

          echo "> 원격저장소에서 브랜치 가져옴"

          git remote update

          echo "> Git 브랜치 명 변경(임시)"

          git checkout main

          CURRENT_PID=$(pgrep -f IT-Hermes-Crawling)
          echo "$CURRENT_PID"

          if [ -z $CURRENT_PID ]; then
              echo "> 현재 구동중인 Crawling 애플리케이션이 없으므로 종료하지 않습니다."
          else
              echo "> 현재서비스 종료 (kill -9 $CURRENT_PID)"
              kill -9 $CURRENT_PID
              sleep 5
          fi

          echo "> 새 어플리케이션 배포"

          nohup node $REPOSITORY/IT-Hermes-Crawling/app.js &
